"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Default is long enough for HS256 JWT (≥32 bytes). Override in production via env.
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-assetflow-dev-key-change-me-32b+",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

# Comma-separated list in env; defaults allow local dev + Django test client.
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "0.0.0.0", "testserver"],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "apps.authentication",
    "apps.organization",
    "apps.assets",
    "apps.audits",
    "apps.dashboard",
    "apps.resource_allocation",
    "apps.maintenance",
    "apps.booking",
    "apps.activity",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB", default="app"),
        "USER": env("POSTGRES_USER", default="app"),
        "PASSWORD": env("POSTGRES_PASSWORD", default="app"),
        "HOST": env("POSTGRES_HOST", default="localhost"),
        "PORT": env("POSTGRES_PORT", default="5432"),
    }
}


# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/
#
# In-process local memory cache. Used by the OTP flow. Fine for dev and
# single-process deploys; swap the backend if you need multi-process sharing.

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "assetflow-default",
    }
}


# Custom user model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = "authentication.User"


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


# drf-spectacular (OpenAPI schema + Swagger/ReDoc UI)
# https://drf-spectacular.readthedocs.io/en/latest/settings.html

SPECTACULAR_SETTINGS = {
    "TITLE": "Sparkz AssetFlow API",
    "DESCRIPTION": (
        "Enterprise **Asset & Resource Management** REST API.\n\n"
        "### Auth\n"
        "Most endpoints require `Authorization: Bearer <access_token>`.\n"
        "Obtain tokens via **Authentication** (`/api/auth/login/` etc.). "
        "Refresh uses an httpOnly cookie (`POST /api/auth/refresh/`).\n\n"
        "### Roles\n"
        "`admin` · `asset_manager` · `department_head` · `employee`\n\n"
        "### UIs\n"
        "- Swagger: `/api/docs/`\n"
        "- ReDoc: `/api/redoc/`\n"
        "- Raw OpenAPI: `/api/schema/`\n"
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api",
    "SORT_OPERATIONS": False,
    "TAGS": [
        {
            "name": "Authentication",
            "description": "Signup, login, OTP, password reset, JWT session.",
        },
        {
            "name": "Organization / Departments",
            "description": "Admin CRUD for departments.",
        },
        {
            "name": "Organization / Categories",
            "description": "Admin CRUD for asset categories.",
        },
        {
            "name": "Organization / Employees",
            "description": "Employee directory + role/status/department assignment.",
        },
        {
            "name": "Assets",
            "description": "Physical asset catalog, registration, lifecycle status.",
        },
        {
            "name": "Assets / Locations",
            "description": "Physical locations for assets and audit scoping.",
        },
        {
            "name": "Resources / Assets",
            "description": "Quantity-tracked resource pool catalog (allocate stock).",
        },
        {
            "name": "Resources / Holdings",
            "description": "Who currently holds how much of each resource asset.",
        },
        {
            "name": "Resources / Transfers",
            "description": "Immutable movement ledger.",
        },
        {
            "name": "Resources / Requests",
            "description": "Allocation requests, fulfill / reject / cancel / broadcast.",
        },
        {
            "name": "Resources / Allocate",
            "description": "Push quantity from manager pool (or sub-allocate).",
        },
        {
            "name": "Resources / Return",
            "description": "Return quantity to the manager pool.",
        },
        {
            "name": "Booking",
            "description": "Shared resource bookings with no-overlap constraint.",
        },
        {
            "name": "Maintenance",
            "description": "Maintenance workflow: pending → approved/rejected → in progress → resolved.",
        },
        {
            "name": "Audits / Cycles",
            "description": "Verification cycles: create, assign auditors, close.",
        },
        {
            "name": "Audits / Items",
            "description": "Per-asset verdicts within a cycle.",
        },
        {
            "name": "Audits / Discrepancies",
            "description": "Missing/damaged flags and resolve action.",
        },
        {
            "name": "Dashboard",
            "description": "KPIs, analytics reports, notification feed.",
        },
        {
            "name": "Dashboard / Exports",
            "description": "CSV downloads for operational datasets.",
        },
        {
            "name": "Activity",
            "description": "Persistent activity / audit trail log.",
        },
    ],
}

# ---------------------------------------------------------------------------
# Logging — mirror activity events to backend/logs/activity.log
# ---------------------------------------------------------------------------

LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "activity": {
            "format": "%(asctime)s %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%S%z",
        },
    },
    "handlers": {
        "activity_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "activity.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "activity",
        },
    },
    "loggers": {
        "assetflow.activity": {
            "handlers": ["activity_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# Refresh token cookie
# Read by apps.authentication.tokens when setting/clearing the httpOnly cookie.

REFRESH_COOKIE_NAME = "refresh_token"
REFRESH_COOKIE_SAMESITE = env("REFRESH_COOKIE_SAMESITE", default="Lax")
REFRESH_COOKIE_SECURE = env.bool("REFRESH_COOKIE_SECURE", default=not DEBUG)


# CORS
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=["http://localhost:3000"])
CORS_ALLOW_CREDENTIALS = True


# Email (OTP delivery via Gmail SMTP)
# EMAIL_BACKEND is itself env-driven so it can be flipped to the console
# backend later (django.core.mail.backends.console.EmailBackend) without a
# code change.

EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("GOOGLE_SMTP_PASSWORD", default="")
DEFAULT_FROM_EMAIL = f"RBAC Auth <{EMAIL_HOST_USER}>"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
