# Generated by Django 5.2.16 on 2026-07-12 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_seed_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total_quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('is_bookable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_assets', to='organization.assetcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_holder_type', models.CharField(choices=[('manager', 'Asset Manager (unallocated pool)'), ('department', 'Department'), ('employee', 'Employee')], max_length=16)),
                ('for_holder_id', models.PositiveIntegerField()),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_fulfilled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='resource_allocation.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('manager', 'Asset Manager (unallocated pool)'), ('department', 'Department'), ('employee', 'Employee')], max_length=16)),
                ('holder_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='resource_allocation.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_holder_type', models.CharField(choices=[('manager', 'Asset Manager (unallocated pool)'), ('department', 'Department'), ('employee', 'Employee')], max_length=16)),
                ('from_holder_id', models.PositiveIntegerField()),
                ('to_holder_type', models.CharField(choices=[('manager', 'Asset Manager (unallocated pool)'), ('department', 'Department'), ('employee', 'Employee')], max_length=16)),
                ('to_holder_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('allocate', 'Allocate'), ('sub_allocate', 'Sub-allocate'), ('fulfill_request', 'Fulfill Request'), ('peer_transfer', 'Peer Transfer'), ('return', 'Return')], max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='resource_allocation.asset')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='resource_allocation.allocationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='allocationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_fulfilled__lte', models.F('quantity_requested'))), name='request_fulfilled_lte_requested'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('asset', 'holder_type', 'holder_id'), name='uniq_holding_per_asset_holder'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='holding_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('holder_id', 0), ('holder_type', 'manager')), models.Q(models.Q(('holder_type', 'manager'), _negated=True), ('holder_id__gt', 0)), _connector='OR'), name='holding_holder_id_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_quantity_gt_0'),
        ),
    ]
