# Generated by Django 5.2.16 on 2026-07-12 09:12

import apps.booking.models
import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('booking', '0002_btree_gist'),
        ('organization', '0002_seed_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('upcoming', 'ongoing'))), expressions=[('asset', '='), (apps.booking.models.TstzRange(models.F('starts_at'), models.F('ends_at'), models.Value('[)')), '&&')], name='booking_no_overlap'),
        ),
    ]
